# Generated by Django 3.0.8 on 2020-07-03 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bhiwandi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_joinee', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60, null=True)),
                ('date_of_joinee', models.DateField(default=django.utils.timezone.now)),
                ('current_ou_removed', models.CharField(max_length=60)),
                ('device_assigned', models.CharField(choices=[('L', 'Laptop'), ('D', 'Desktop')], max_length=1)),
                ('mouse_assigned', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('slack_id', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('adobe_id', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('gmail_id', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('office_tools', models.CharField(choices=[('MS', 'MS_OFFICE'), ('W', 'WPS'), ('N', 'NO')], max_length=3)),
                ('device_assigned_by', models.CharField(choices=[('R', 'Rufus'), ('N', 'Nikhil')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lowerparel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_joinee', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60, null=True)),
                ('current_ou', models.CharField(max_length=60)),
                ('date_of_joinee', models.DateField(default=django.utils.timezone.now)),
                ('current_ou_removed', models.CharField(max_length=60)),
                ('device_assigned', models.CharField(choices=[('L', 'Laptop'), ('D', 'Desktop')], max_length=1)),
                ('mouse_assigned', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('slack_id', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('adobe_id', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('gmail_id', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('office_tools', models.CharField(choices=[('MS', 'MS_OFFICE'), ('W', 'WPS'), ('N', 'NO')], max_length=3)),
                ('device_assigned_by', models.CharField(choices=[('R', 'Rufus'), ('N', 'Nikhil')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='STORE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_joinee', models.CharField(max_length=60)),
                ('date_of_joinee', models.DateField(default=django.utils.timezone.now)),
                ('mouse_assigned', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('device_assigned_by', models.CharField(choices=[('R', 'Rufus'), ('N', 'Nikhil')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='V_TECH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ordered', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=3)),
                ('purchase_order_id', models.CharField(max_length=5)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('device_arrived', models.CharField(max_length=100)),
                ('bill_id', models.CharField(max_length=5)),
                ('delivered_quantity', models.CharField(max_length=3)),
                ('received_by', models.CharField(max_length=10)),
                ('device_return', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
